
server:
  port: 8080
spring:
  servlet:
    multipart:
      max-file-size: -1
      max-request-size: -1
  # REDIS数据库配置
  redis:
    #  Redis服务器IP, REDIS安装在本机的,使用127.0.0.1
    host: 127.0.0.1
    # 端口号
    port: 6379
    # 数据库 DB
    database: 6
    # 访问密码,若你的redis服务器没有设置密码，就不需要用密码去连接
    #  password: face2020
    lettuce: # 这里标明使用lettuce配置
      pool:
        max-active: 8   #连接池最大连接数（使用负值表示没有限制）
        max-wait: -1ms  #连接池最大阻塞等待时间（使用负值表示没有限制）
        max-idle: 5     #连接池中的最大空闲连接
        min-idle: 0     #连接池中的最小空闲连接
    # 超时时间
    timeout: 20000
    # mysql数据源
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    type: com.zaxxer.hikari.HikariDataSource
    url: jdbc:mysql://127.0.0.1:3306/zenfile?useUnicode=true&characterEncoding=UTF8&rewriteBatchedStatements=true&serverTimezone=PRC&useSSL=false&allowMultiQueries=true
    username: root
    password: 123456
    hikari:
      connection-timeout: 20000             # 是客户端等待连接池连接的最大毫秒数
      maximum-pool-size: 200                # 连接池最大连接数
      minimum-idle: 5                       # 连接池最小空闲连接数
      idle-timeout: 300000                  # 允许连接在连接池中空闲的最长时间（以毫秒为单位）
      max-lifetime: 1200000                 # 是池中连接关闭后的最长生命周期（以毫秒为单位)
  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher

knife4j:
  enable: true
  setting:
    enableSwaggerModels: true

mybatis:
  mapper-locations: classpath:/mapper/*.xml
  type-handlers-package: org.zenfile.utils
  configuration:
    map-underscore-to-camel-case: true

zenfile:
  log:
    home: ./logs
    encoder: UTF-8
